import React, { useMemo, useState, useEffect } from 'react';
import { useCart } from '@/contexts/CartContext';
import { pharmacyAPI } from '@/lib/api';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectTrigger, SelectContent, SelectItem, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/contexts/AuthContext';

const Checkout: React.FC = () => {
  const { items, total, clear } = useCart();
  const { user } = useAuth();
  const { toast } = useToast();
  const [name, setName] = useState(user?.name || '');
  const [phone, setPhone] = useState(user?.phone || '');
  const [addressLine, setAddressLine] = useState((user as any)?.address || '');
  const [city, setCity] = useState('');
  const [postal, setPostal] = useState('');
  const [useProfile, setUseProfile] = useState(true);
  const [paymentMethod, setPaymentMethod] = useState<'card' | 'cod' | 'upi'>('card');
  const [cardName, setCardName] = useState('');
  const [cardNumber, setCardNumber] = useState('');
  const [cardExpiry, setCardExpiry] = useState('');
  const [cardCvv, setCardCvv] = useState('');
  const [promo, setPromo] = useState('');
  const [appliedPromo, setAppliedPromo] = useState<string | null>(null);
  const [discount, setDiscount] = useState(0);
  const [shipping, setShipping] = useState(5);
  const [agree, setAgree] = useState(false);
  const [rxFileName, setRxFileName] = useState<string | null>(null);
  const [rxData, setRxData] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const hasRx = useMemo(() => items.some((i) => (i as any).requiresPrescription), [items]);

  const addressText = useMemo(() => {
    const parts = [name, phone, addressLine, city, postal].filter(Boolean);
    return parts.join(', ');
  }, [name, phone, addressLine, city, postal]);

  const subtotal = useMemo(() => total(), [items, total]);
  const grandTotal = useMemo(() => Math.max(0, subtotal - discount) + shipping, [subtotal, discount, shipping]);

  const applyPromo = () => {
    const code = promo.trim().toUpperCase();
    if (!code) return;
    if (code === 'SAVE10') {
      setDiscount(Math.round(subtotal * 0.1 * 100) / 100);
      setAppliedPromo(code);
      toast({ title: 'Promo applied', description: '10% discount applied' });
    } else if (code === 'FREESHIP') {
      setShipping(0);
      setAppliedPromo(code);
      toast({ title: 'Promo applied', description: 'Free shipping applied' });
    } else {
      setDiscount(0);
      setAppliedPromo(null);
      toast({ title: 'Invalid code', description: 'Try SAVE10 or FREESHIP', variant: 'destructive' });
    }
  };

  // Generate UPI QR code when UPI ID changes - NO LONGER NEEDED
  // QR code will be generated by backend after order creation
  
  const handleRxUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0];
    if (!f) return;
    setRxFileName(f.name);
    const reader = new FileReader();
    reader.onload = () => setRxData(String(reader.result));
    reader.readAsDataURL(f);
  };

  const validatePayment = () => {
    if (paymentMethod === 'card') {
      if (!cardName || !cardNumber || !cardExpiry || !cardCvv) return false;
      if (!/^[0-9]{16}$/.test(cardNumber.replace(/\s+/g, ''))) return false;
      if (!/^[0-9]{3,4}$/.test(cardCvv)) return false;
      return true;
    }
    if (paymentMethod === 'upi') {
      // UPI validation - merchant UPI is configured on backend
      return true;
    }
    return true;
  };

  const handlePlaceOrder = async () => {
    if (items.length === 0) return toast({ title: 'Cart is empty', variant: 'destructive' });
    if (!name || !phone || !addressLine || !city || !postal) return toast({ title: 'Enter full delivery details', variant: 'destructive' });
    if (hasRx && !rxData) return toast({ title: 'Prescription required', description: 'Upload a valid prescription to proceed', variant: 'destructive' });
    if (!agree) return toast({ title: 'Confirm policies', description: 'Accept terms to place order', variant: 'destructive' });
    if (!validatePayment()) return toast({ title: 'Payment details invalid', variant: 'destructive' });

    const order = {
      subtotal,
      discount,
      shipping,
      total: grandTotal,
      shippingAddress: addressText,
      items: items.map((i) => ({ productId: i.productId, quantity: i.quantity, price: i.price, name: i.name })),
      payment: paymentMethod === 'card'
        ? { method: 'card', brand: 'VISA', last4: cardNumber.slice(-4) }
        : paymentMethod === 'upi'
        ? { method: 'upi' }
        : { method: 'cod' },
      prescription: hasRx ? { fileName: rxFileName, dataUrl: rxData } : null,
      promo: appliedPromo,
    };

    try {
      setLoading(true);
      const res = await pharmacyAPI.createOrder(order);
      const orderId = res.data?.id;
      clear();
      toast({ title: 'Order placed', description: 'Redirecting to payment...' });
      
      // For UPI payments, redirect to payment page to show QR code
      if (paymentMethod === 'upi' && orderId) {
        navigate(`/payment/${orderId}`);
      } else {
        navigate('/dashboard');
      }
    } catch (err) {
      console.error('Failed to place order', err);
      toast({ title: 'Failed to place order', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6 max-w-3xl space-y-6">
      <h1 className="text-3xl font-bold">Checkout</h1>

      <Card>
        <CardHeader>
          <CardTitle>Delivery Details</CardTitle>
          <CardDescription>Provide recipient and address information</CardDescription>
        </CardHeader>
        <CardContent className="grid md:grid-cols-2 gap-4">
          <div className="flex items-center gap-2">
            <Checkbox checked={useProfile} onCheckedChange={(v) => setUseProfile(!!v)} />
            <span className="text-sm">Use profile info</span>
          </div>
          <div className="md:col-span-2 grid md:grid-cols-2 gap-4">
            <div>
              <label className="text-sm">Name</label>
              <Input value={name} onChange={(e) => setName(e.target.value)} />
            </div>
            <div>
              <label className="text-sm">Phone</label>
              <Input value={phone} onChange={(e) => setPhone(e.target.value)} />
            </div>
            <div className="md:col-span-2">
              <label className="text-sm">Address</label>
              <Textarea value={addressLine} onChange={(e) => setAddressLine(e.target.value)} />
            </div>
            <div>
              <label className="text-sm">City</label>
              <Input value={city} onChange={(e) => setCity(e.target.value)} />
            </div>
            <div>
              <label className="text-sm">Postal Code</label>
              <Input value={postal} onChange={(e) => setPostal(e.target.value)} />
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Payment</CardTitle>
          <CardDescription>Select a method and provide details</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <label className="text-sm">Payment Method</label>
            <Select value={paymentMethod} onValueChange={(v) => setPaymentMethod(v as any)}>
              <SelectTrigger className="w-64">
                <SelectValue placeholder="Select method" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="card">Card</SelectItem>
                <SelectItem value="upi">UPI</SelectItem>
                <SelectItem value="cod">Cash on Delivery</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {paymentMethod === 'card' ? (
            <div className="grid md:grid-cols-2 gap-4">
              <div className="md:col-span-2">
                <label className="text-sm">Name on Card</label>
                <Input value={cardName} onChange={(e) => setCardName(e.target.value)} />
              </div>
              <div className="md:col-span-2">
                <label className="text-sm">Card Number</label>
                <Input value={cardNumber} onChange={(e) => setCardNumber(e.target.value.replace(/[^0-9]/g, ''))} placeholder="1234123412341234" />
              </div>
              <div>
                <label className="text-sm">Expiry (MM/YY)</label>
                <Input value={cardExpiry} onChange={(e) => setCardExpiry(e.target.value)} placeholder="12/29" />
              </div>
              <div>
                <label className="text-sm">CVV</label>
                <Input value={cardCvv} onChange={(e) => setCardCvv(e.target.value.replace(/[^0-9]/g, ''))} placeholder="123" />
              </div>
            </div>
          ) : null}

          {paymentMethod === 'upi' ? (
            <div className="grid md:grid-cols-2 gap-4">
              <div className="md:col-span-2 rounded-lg bg-blue-50 p-4 border border-blue-200">
                <div className="text-sm text-blue-900">
                  <strong>💳 UPI Payment</strong><br/>
                  A unique QR code with merchant's UPI ID and amount ₹{grandTotal.toFixed(2)} will be generated after you place the order. Simply scan it with any UPI app (Google Pay, PhonePe, Paytm, etc.) to complete payment.
                </div>
              </div>
            </div>
          ) : null}

          {hasRx ? (
            <div className="grid md:grid-cols-2 gap-4">
              <div className="md:col-span-2">
                <div className="flex items-center gap-2">
                  <Badge variant="destructive">RX</Badge>
                  <span className="text-sm">Prescription items detected</span>
                </div>
                <div className="mt-2">
                  <input type="file" accept="image/*,application/pdf" onChange={handleRxUpload} />
                  {rxFileName ? <div className="text-xs text-muted-foreground mt-1">{rxFileName}</div> : null}
                </div>
              </div>
            </div>
          ) : null}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Order Summary</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            {items.map((i) => (
              <div key={i.productId} className="flex items-center justify-between">
                <div className="text-sm">{i.name} × {i.quantity}</div>
                <div className="text-sm">₹{(i.price * i.quantity).toFixed(2)}</div>
              </div>
            ))}
          </div>

          <div className="grid md:grid-cols-2 gap-4 items-end">
            <div>
              <label className="text-sm">Promo Code</label>
              <div className="flex gap-2">
                <Input value={promo} onChange={(e) => setPromo(e.target.value)} placeholder="SAVE10 or FREESHIP" />
                <Button variant="outline" onClick={applyPromo}>Apply</Button>
              </div>
              {appliedPromo ? <div className="text-xs text-muted-foreground mt-1">Applied: {appliedPromo}</div> : null}
            </div>
            <div className="text-sm md:text-right space-y-1">
              <div>Subtotal: ₹{subtotal.toFixed(2)}</div>
              <div>Discount: -₹{discount.toFixed(2)}</div>
              <div>Shipping: ₹{shipping.toFixed(2)}</div>
              <div className="text-xl font-bold">Total: ${grandTotal.toFixed(2)}</div>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Checkbox checked={agree} onCheckedChange={(v) => setAgree(!!v)} />
            <span className="text-sm">I agree to the terms and refund policy</span>
          </div>

          <div className="flex items-center justify-end">
            <Button onClick={handlePlaceOrder} disabled={loading}>{loading ? 'Placing…' : 'Place Order'}</Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default Checkout;
